-- Migration 001: Vendor-Agnostic Schema Extension
-- Purpose: Extend Claude-specific SessionLogger schema to support multiple AI vendors
-- Date: 2025-11-24
-- Version: 2.0.0

-- =============================================================================
-- PART 1: New Tables for Vendor-Agnostic Tracking
-- =============================================================================

-- Vendor registry: Track all AI assistant vendors (built-in and plugins)
CREATE TABLE IF NOT EXISTS vendor_profiles (
    vendor_id TEXT PRIMARY KEY,                    -- 'claude', 'gemini', 'openai', 'custom-xyz'
    vendor_name TEXT NOT NULL,                     -- 'Claude Code', 'Gemini CLI', etc.
    vendor_type TEXT NOT NULL CHECK(vendor_type IN ('builtin', 'plugin')),
    config_dir TEXT NOT NULL,                      -- ~/.claude, ~/.gemini, etc.
    executable_name TEXT,                          -- 'claude', 'gemini', 'codex'
    is_active BOOLEAN DEFAULT TRUE,
    metadata JSON,                                 -- Vendor-specific metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Vendor versions/models: Track different models and their costs
CREATE TABLE IF NOT EXISTS vendor_versions (
    version_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vendor_id TEXT NOT NULL,
    model_name TEXT NOT NULL,                     -- 'claude-sonnet-4', 'gemini-2.0-flash', 'gpt-4'
    api_version TEXT,                             -- API version if applicable
    cost_per_input_token REAL,                    -- Cost in USD per 1M tokens
    cost_per_output_token REAL,                   -- Cost in USD per 1M tokens
    rate_limit_rpm INTEGER,                       -- Requests per minute
    rate_limit_tpm INTEGER,                       -- Tokens per minute
    capabilities JSON,                            -- Features: agents, mcp, tools, etc.
    active_from TIMESTAMP NOT NULL,
    active_until TIMESTAMP,                       -- NULL = currently active
    FOREIGN KEY (vendor_id) REFERENCES vendor_profiles(vendor_id) ON DELETE CASCADE,
    UNIQUE(vendor_id, model_name, api_version)
);

-- Session costs: Track token usage and costs per session
CREATE TABLE IF NOT EXISTS session_costs (
    cost_id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    vendor_id TEXT NOT NULL,
    vendor_version_id INTEGER,
    input_tokens INTEGER DEFAULT 0,
    output_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER GENERATED ALWAYS AS (input_tokens + output_tokens) STORED,
    cost_usd REAL,                                -- Calculated cost
    rate_limit_hits INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES vendor_profiles(vendor_id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_version_id) REFERENCES vendor_versions(version_id) ON DELETE SET NULL
);

-- GitHub integrations: Track GitHub activity generated by vendors
CREATE TABLE IF NOT EXISTS github_integrations (
    integration_id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    vendor_id TEXT NOT NULL,
    actor_type TEXT NOT NULL CHECK(actor_type IN (
        'human',
        'ai_agent_local',
        'ai_agent_github_actions',
        'ai_agent_scheduled',
        'system'
    )),
    activity_type TEXT NOT NULL CHECK(activity_type IN (
        'issue_created',
        'issue_commented',
        'pr_created',
        'pr_reviewed',
        'commit_made',
        'branch_created',
        'tag_created'
    )),
    github_url TEXT NOT NULL,
    github_id TEXT,                               -- Issue #123, PR #456, commit SHA
    resource_title TEXT,
    metadata JSON,                                -- Additional activity-specific data
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES vendor_profiles(vendor_id) ON DELETE CASCADE
);

-- Polymorphic capabilities: Agents, skills, MCP servers, tools
CREATE TABLE IF NOT EXISTS capabilities (
    capability_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vendor_id TEXT NOT NULL,
    capability_type TEXT NOT NULL CHECK(capability_type IN (
        'agent',
        'skill',
        'mcp_server',
        'tool',
        'custom'
    )),
    capability_name TEXT NOT NULL,
    display_name TEXT,
    description TEXT,
    file_path TEXT,                               -- Path to definition file
    config JSON,                                  -- Capability-specific configuration
    metadata JSON,                                -- Vendor-specific fields
    is_active BOOLEAN DEFAULT TRUE,
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vendor_id, capability_type, capability_name),
    FOREIGN KEY (vendor_id) REFERENCES vendor_profiles(vendor_id) ON DELETE CASCADE
);

-- =============================================================================
-- PART 2: Extend Existing Tables (Add Vendor Columns)
-- =============================================================================

-- Add vendor tracking columns to sessions table
ALTER TABLE sessions ADD COLUMN vendor_id TEXT NOT NULL DEFAULT 'claude';
ALTER TABLE sessions ADD COLUMN vendor_version TEXT;
ALTER TABLE sessions ADD COLUMN actor_type TEXT NOT NULL DEFAULT 'human'
    CHECK(actor_type IN ('human', 'ai_agent_local', 'ai_agent_github_actions', 'ai_agent_scheduled', 'system'));
ALTER TABLE sessions ADD COLUMN execution_context TEXT NOT NULL DEFAULT 'local_dev'
    CHECK(execution_context IN ('local_dev', 'github_actions', 'scheduled_job', 'web_dashboard', 'cli'));
ALTER TABLE sessions ADD COLUMN is_self_development BOOLEAN DEFAULT FALSE;

-- Add vendor tracking to events table
ALTER TABLE events ADD COLUMN vendor_id TEXT NOT NULL DEFAULT 'claude';

-- =============================================================================
-- PART 3: Rename Claude-Specific Tables
-- =============================================================================

-- Rename to make vendor-specific naming clear
ALTER TABLE subagent_profiles RENAME TO claude_agent_profiles;
ALTER TABLE skill_profiles RENAME TO claude_skill_profiles;

-- =============================================================================
-- PART 4: Create Indices for Performance
-- =============================================================================

-- Vendor profiles
CREATE INDEX IF NOT EXISTS idx_vendor_profiles_type ON vendor_profiles(vendor_type, is_active);

-- Vendor versions
CREATE INDEX IF NOT EXISTS idx_vendor_versions_active ON vendor_versions(vendor_id, active_until)
    WHERE active_until IS NULL;

-- Session costs
CREATE INDEX IF NOT EXISTS idx_session_costs_vendor ON session_costs(vendor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_session_costs_session ON session_costs(session_id);

-- GitHub integrations
CREATE INDEX IF NOT EXISTS idx_github_vendor_activity ON github_integrations(vendor_id, activity_type, created_at);
CREATE INDEX IF NOT EXISTS idx_github_actor ON github_integrations(actor_type, created_at);
CREATE INDEX IF NOT EXISTS idx_github_session ON github_integrations(session_id);

-- Capabilities
CREATE INDEX IF NOT EXISTS idx_capabilities_vendor_type ON capabilities(vendor_id, capability_type, is_active);
CREATE INDEX IF NOT EXISTS idx_capabilities_usage ON capabilities(usage_count DESC, last_used_at);

-- Sessions (vendor queries)
CREATE INDEX IF NOT EXISTS idx_sessions_vendor ON sessions(vendor_id, start_time);
CREATE INDEX IF NOT EXISTS idx_sessions_actor ON sessions(actor_type, execution_context);
CREATE INDEX IF NOT EXISTS idx_sessions_self_dev ON sessions(is_self_development, vendor_id)
    WHERE is_self_development = TRUE;

-- Events (vendor queries)
CREATE INDEX IF NOT EXISTS idx_events_vendor ON events(vendor_id, event_type, timestamp);

-- =============================================================================
-- PART 5: Seed Default Vendor Data
-- =============================================================================

-- Insert built-in vendor profiles
INSERT OR IGNORE INTO vendor_profiles (vendor_id, vendor_name, vendor_type, config_dir, executable_name, metadata) VALUES
    ('claude', 'Claude Code', 'builtin', '~/.claude', 'claude', json('{"supports_agents": true, "supports_mcp": true}')),
    ('gemini', 'Gemini CLI', 'builtin', '~/.gemini', 'gemini', json('{"supports_agents": false, "supports_mcp": true}')),
    ('openai', 'OpenAI Codex', 'builtin', '~/.codex', 'codex', json('{"supports_agents": true, "supports_mcp": true}'));

-- Insert vendor versions with cost data (as of 2025-11-24)
INSERT OR IGNORE INTO vendor_versions (vendor_id, model_name, cost_per_input_token, cost_per_output_token, active_from, capabilities) VALUES
    ('claude', 'claude-sonnet-4-5-20250929', 3.0, 15.0, '2024-09-29', json('{"max_tokens": 8192, "supports_vision": true}')),
    ('claude', 'claude-opus-4-5-20251101', 15.0, 75.0, '2024-11-01', json('{"max_tokens": 8192, "supports_vision": true}')),
    ('gemini', 'gemini-2.0-flash', 0.0, 0.0, '2024-12-01', json('{"max_tokens": 8192, "free_tier": true}')),
    ('gemini', 'gemini-pro', 0.5, 1.5, '2024-01-01', json('{"max_tokens": 32768}')),
    ('openai', 'gpt-4-turbo', 10.0, 30.0, '2024-04-01', json('{"max_tokens": 128000}'));

-- Migrate existing agent profiles to capabilities table
INSERT OR IGNORE INTO capabilities (vendor_id, capability_type, capability_name, description, file_path, metadata)
SELECT
    'claude' as vendor_id,
    'agent' as capability_type,
    name as capability_name,
    description,
    file_path,
    json_object(
        'model', model,
        'version', version,
        'tools', tools,
        'tags', tags,
        'category', category
    ) as metadata
FROM claude_agent_profiles;

-- Migrate existing skill profiles to capabilities table
INSERT OR IGNORE INTO capabilities (vendor_id, capability_type, capability_name, description, file_path, metadata)
SELECT
    'claude' as vendor_id,
    'skill' as capability_type,
    name as capability_name,
    description,
    file_path,
    json_object(
        'version', version,
        'tags', tags,
        'directory', directory,
        'category', category,
        'auto_invoke', auto_invoke
    ) as metadata
FROM claude_skill_profiles;

-- =============================================================================
-- PART 6: Update Schema Metadata
-- =============================================================================

-- Update schema version to indicate vendor-agnostic migration
INSERT OR REPLACE INTO schema_metadata (key, value, updated_at) VALUES
    ('version', '2.0.0', CURRENT_TIMESTAMP),
    ('phase', 'Vendor-Agnostic', CURRENT_TIMESTAMP),
    ('migration', '001_vendor_agnostic', CURRENT_TIMESTAMP),
    ('description', 'Extended schema to support multiple AI vendors (Claude, Gemini, OpenAI, plugins)', CURRENT_TIMESTAMP);

-- =============================================================================
-- PART 7: Create New Analytical Views
-- =============================================================================

-- Vendor comparison view
CREATE VIEW IF NOT EXISTS vendor_comparison AS
SELECT
    v.vendor_id,
    v.vendor_name,
    COUNT(DISTINCT s.session_id) as total_sessions,
    SUM(sc.input_tokens) as total_input_tokens,
    SUM(sc.output_tokens) as total_output_tokens,
    SUM(sc.cost_usd) as total_cost_usd,
    AVG(CASE WHEN s.end_time IS NOT NULL
        THEN (julianday(s.end_time) - julianday(s.start_time)) * 24 * 60
        ELSE NULL END) as avg_duration_minutes,
    COUNT(CASE WHEN s.outcome = 'completed' THEN 1 END) as successful_sessions,
    COUNT(CASE WHEN s.outcome = 'failed' THEN 1 END) as failed_sessions,
    ROUND(100.0 * COUNT(CASE WHEN s.outcome = 'completed' THEN 1 END) / COUNT(*), 2) as success_rate_pct
FROM vendor_profiles v
LEFT JOIN sessions s ON v.vendor_id = s.vendor_id
LEFT JOIN session_costs sc ON s.session_id = sc.session_id
GROUP BY v.vendor_id, v.vendor_name;

-- Cost analysis view
CREATE VIEW IF NOT EXISTS cost_analysis AS
SELECT
    sc.vendor_id,
    v.vendor_name,
    vv.model_name,
    date(sc.created_at) as date,
    COUNT(sc.session_id) as sessions,
    SUM(sc.input_tokens) as input_tokens,
    SUM(sc.output_tokens) as output_tokens,
    SUM(sc.total_tokens) as total_tokens,
    SUM(sc.cost_usd) as cost_usd,
    AVG(sc.cost_usd) as avg_cost_per_session
FROM session_costs sc
JOIN vendor_profiles v ON sc.vendor_id = v.vendor_id
LEFT JOIN vendor_versions vv ON sc.vendor_version_id = vv.version_id
GROUP BY sc.vendor_id, v.vendor_name, vv.model_name, date(sc.created_at);

-- GitHub attribution view
CREATE VIEW IF NOT EXISTS github_attribution AS
SELECT
    gi.vendor_id,
    v.vendor_name,
    gi.actor_type,
    gi.activity_type,
    COUNT(*) as activity_count,
    COUNT(DISTINCT gi.session_id) as sessions,
    MIN(gi.created_at) as first_activity,
    MAX(gi.created_at) as last_activity
FROM github_integrations gi
JOIN vendor_profiles v ON gi.vendor_id = v.vendor_id
GROUP BY gi.vendor_id, v.vendor_name, gi.actor_type, gi.activity_type;

-- Agent/capability performance across all vendors
CREATE VIEW IF NOT EXISTS capability_performance AS
SELECT
    c.vendor_id,
    v.vendor_name,
    c.capability_type,
    c.capability_name,
    c.usage_count,
    c.last_used_at,
    CASE
        WHEN c.last_used_at IS NULL THEN 'Never Used'
        WHEN julianday('now') - julianday(c.last_used_at) > 30 THEN 'Underutilized'
        WHEN julianday('now') - julianday(c.last_used_at) > 7 THEN 'Occasional'
        ELSE 'Active'
    END as usage_category
FROM capabilities c
JOIN vendor_profiles v ON c.vendor_id = v.vendor_id
WHERE c.is_active = TRUE
ORDER BY c.usage_count DESC;

-- =============================================================================
-- MIGRATION COMPLETE
-- =============================================================================

-- Verify migration success
SELECT
    'Migration 001 Complete' as status,
    (SELECT COUNT(*) FROM vendor_profiles) as vendor_count,
    (SELECT COUNT(*) FROM vendor_versions) as version_count,
    (SELECT COUNT(*) FROM capabilities) as capability_count,
    (SELECT value FROM schema_metadata WHERE key = 'version') as schema_version;
